# Cloud Build configuration for Uplevel Financial Intelligence Agent
# Builds container and deploys to Vertex AI Agent Engine via Cloud Run

steps:
  # Step 1: Build the container image
  - name: 'gcr.io/cloud-builders/docker'
    args:
      - 'build'
      - '-t'
      - '${_REGION}-docker.pkg.dev/${PROJECT_ID}/${_REPOSITORY}/uplevel-financial-agent:${SHORT_SHA:-latest}'
      - '-t'
      - '${_REGION}-docker.pkg.dev/${PROJECT_ID}/${_REPOSITORY}/uplevel-financial-agent:latest'
      - '-f'
      - 'deployment/Dockerfile'
      - '.'

  # Step 2: Push the container image
  - name: 'gcr.io/cloud-builders/docker'
    args:
      - 'push'
      - '${_REGION}-docker.pkg.dev/${PROJECT_ID}/${_REPOSITORY}/uplevel-financial-agent:${SHORT_SHA:-latest}'

  - name: 'gcr.io/cloud-builders/docker'
    args:
      - 'push'
      - '${_REGION}-docker.pkg.dev/${PROJECT_ID}/${_REPOSITORY}/uplevel-financial-agent:latest'

  # Step 3: Deploy to Cloud Run
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: gcloud
    args:
      - 'run'
      - 'deploy'
      - 'uplevel-financial-agent'
      - '--image'
      - '${_REGION}-docker.pkg.dev/${PROJECT_ID}/${_REPOSITORY}/uplevel-financial-agent:${SHORT_SHA:-latest}'
      - '--region'
      - '${_REGION}'
      - '--platform'
      - 'managed'
      - '--allow-unauthenticated'
      - '--port'
      - '8080'
      - '--memory'
      - '2Gi'
      - '--cpu'
      - '1000m'
      - '--min-instances'
      - '1'
      - '--max-instances'
      - '10'
      - '--timeout'
      - '300s'
      - '--set-env-vars'
      - 'GOOGLE_CLOUD_PROJECT=${PROJECT_ID}'
      - '--set-env-vars'
      - 'VERTEX_AI_LOCATION=${_REGION}'

  # Step 4: Configure Vertex AI Agent Engine (using gcloud AI Platform)
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: 'bash'
    args:
      - '-c'
      - |
        # Get the Cloud Run service URL
        SERVICE_URL=$$(gcloud run services describe uplevel-financial-agent --region=${_REGION} --format="value(status.url)")
        
        echo "Cloud Run service deployed at: $$SERVICE_URL"
        echo "Setting up Vertex AI Agent Engine integration..."
        
        # Note: Actual Vertex AI Agent Engine setup would require additional configuration
        # This is a placeholder for the integration steps
        
        echo "Deployment completed successfully!"
        echo "Agent endpoint: $$SERVICE_URL"
        echo "Health check: $$SERVICE_URL/health"
        echo "API docs: $$SERVICE_URL/docs"

# Configuration
options:
  logging: CLOUD_LOGGING_ONLY
  machineType: 'E2_HIGHCPU_8'

# Substitutions (can be overridden)
substitutions:
  _REGION: us-central1
  _REPOSITORY: uplevel-agents

# Timeout
timeout: '1200s'

# Images to be pushed to registry
images:
  - '${_REGION}-docker.pkg.dev/${PROJECT_ID}/${_REPOSITORY}/uplevel-financial-agent:${SHORT_SHA:-latest}'
  - '${_REGION}-docker.pkg.dev/${PROJECT_ID}/${_REPOSITORY}/uplevel-financial-agent:latest'
